[package]
name = "spin-loader"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bindle = { git = "https://github.com/deislabs/bindle", branch = "main", default-features = false, features = ["client"] }
bytes = "1.1.0"
dirs = "4.0.0"
futures = "0.3.17"
glob = "0.3.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
outbound-http = { path = "../outbound-http" }
path-absolutize = "3.0.11"
regex = "1.5.4"
reqwest = "0.11.9"
sha2 = "0.10.1"
semver = "1.0.14"
serde = { version = "1.0", features = [ "derive" ] }
spin-config = { path = "../config" }
spin-manifest = { path = "../manifest" }
tempfile = "3.3.0"
tokio = { version = "1.11", features = [ "full" ] }
tokio-util = "0.7.4"
toml = "0.5"
tracing = { version = "0.1", features = [ "log" ] }
url = "2.2.2"
walkdir = "2.3.2"
